name: docker-compose
description: Multi-container Docker applications
type: cli
homepage: https://github.com/docker/compose
repository: ochairo/potions
license: Unknown
tags:
- container
binaries:
- docker-compose-*
platforms:
  darwin:
    amd64:
      download_url: https://github.com/ochairo/potions/releases/download/docker-compose-{version}/docker-compose-{version}-darwin-x86_64.tar.gz
      checksum_url: https://github.com/ochairo/potions/releases/download/docker-compose-{version}/docker-compose-{version}-darwin-x86_64.tar.gz.sha256
      requires_build: false
    arm64:
      download_url: https://github.com/ochairo/potions/releases/download/docker-compose-{version}/docker-compose-{version}-darwin-arm64.tar.gz
      checksum_url: https://github.com/ochairo/potions/releases/download/docker-compose-{version}/docker-compose-{version}-darwin-arm64.tar.gz.sha256
      requires_build: false
  linux:
    amd64:
      download_url: https://github.com/ochairo/potions/releases/download/docker-compose-{version}/docker-compose-{version}-linux-amd64.tar.gz
      checksum_url: https://github.com/ochairo/potions/releases/download/docker-compose-{version}/docker-compose-{version}-linux-amd64.tar.gz.sha256
      requires_build: false
    arm64:
      download_url: https://github.com/ochairo/potions/releases/download/docker-compose-{version}/docker-compose-{version}-linux-arm64.tar.gz
      checksum_url: https://github.com/ochairo/potions/releases/download/docker-compose-{version}/docker-compose-{version}-linux-arm64.tar.gz.sha256
      requires_build: false
