name: pkg-config
description: pkg-config for managing compile/link flags
type: cli
homepage: https://pkgconfig.freedesktop.org/
repository: ochairo/potions
license: Unknown
tags:
- cli
binaries:
- pkg-config
platforms:
  darwin:
    amd64:
      download_url: https://github.com/ochairo/potions/releases/download/pkg-config-{version}/pkg-config-{version}-darwin-x86_64.tar.gz
      checksum_url: https://github.com/ochairo/potions/releases/download/pkg-config-{version}/pkg-config-{version}-darwin-x86_64.tar.gz.sha256
      requires_build: false
    arm64:
      download_url: https://github.com/ochairo/potions/releases/download/pkg-config-{version}/pkg-config-{version}-darwin-arm64.tar.gz
      checksum_url: https://github.com/ochairo/potions/releases/download/pkg-config-{version}/pkg-config-{version}-darwin-arm64.tar.gz.sha256
      requires_build: false
  linux:
    amd64:
      download_url: https://github.com/ochairo/potions/releases/download/pkg-config-{version}/pkg-config-{version}-linux-amd64.tar.gz
      checksum_url: https://github.com/ochairo/potions/releases/download/pkg-config-{version}/pkg-config-{version}-linux-amd64.tar.gz.sha256
      requires_build: false
    arm64:
      download_url: https://github.com/ochairo/potions/releases/download/pkg-config-{version}/pkg-config-{version}-linux-arm64.tar.gz
      checksum_url: https://github.com/ochairo/potions/releases/download/pkg-config-{version}/pkg-config-{version}-linux-arm64.tar.gz.sha256
      requires_build: false
